use_ffcv:
  desc: set to True to use ffcv compressed datasets
  value: True

dataset_splits:
  value: [ "train", "val", "test_sport", "test_cooking_tokyo", "test_knit" ]
dataset_csvs:
  value: ["training.csv", "validation.csv", "test_sport.csv", "test_cooking_tokyo.csv", "test_knit.csv"]
dataset_ffcvs:
  value: [ "train.beton", "val.beton", "test_sport.beton", "test_cooking_tokyo.beton", "test_knit.beton" ]

ffcv_pre_shuffle:
  desc: shuffle dataset before encoding
  value: True
ffcv_path:
  desc: ffcv base directory
  value: /user/work/qh22492/ego4d/ffcv/sub3_bef0/
ffcv_order:
  desc: Order used for training. Evaluation is always sequential. RANDOM, QUASI_RANDOM or SEQUENTIAL.
  value: QUASI_RANDOM
ffcv_os_cache:
  desc: Set to true if whole dataset fits in memory (and use RANDOM).
  value: False


csv_path:
  desc: Action annotation csv
  value: /user/work/qh22492/e4d/csv_files
csv_shuffle:
  desc: shuffle the dataloader for csv files
  value: True
csv_len:
  desc: only load n samples (useful for debugging). Set to -1 to ignore and use the full dataset.
  value: -1

feat_path:
  desc: Path to flattened features
  value: /user/work/qh22492/Ego4d/ego4d_data/v1/slowfast8x8_r101_k400

sample_mode:
  desc: How to sample features for a given action. E.g. start takes the first feature.
  value: customized

n_action_subsample:
  desc: Sequence length of loaded features inside the segment narration.
  value: 3

n_before_after_context:
  desc: Sequence length of loaded features before/after.
  value: 0



labels:
  desc: Labels returned by the dataloader. Should include action label first, followed by domain labels.
  value: ['label_idx', 'scenario_idx', 'source_idx']

model:
  desc: The model to use. Names as in model.py
  value: MLP

mlp_hidden_dims: 
  desc: Dimensions of hidden layers in mlp. Needs at least one dimension.
  value: [256, 256]
mlp_dropout: 
  desc: dropout prob for use in mlp hidden layers
  value: 0.5
reduce_dim:
  desc: reducing feature dim before concatenating
  value: False
reduced_dim:
  desc: dim of the reduced feature vector
  value: 1024


trn_scales:
  desc: number of different scales for TRN-multiscale
  value: 3

trn_bottleneck:
  desc: TRN bottleneck dimension
  value: 256
trn_classifier:
  desc: number of different scales for TRN-multiscale
  value: True

loss:
  desc: Loss function to use from losses.py
  value: CE
LA_tau:
  value: 1.0

batch_size:
  value: 128

optimizer:
  value: Adam

sch_milestones:
  value: [70,90]

sch_gamma:
  value: 0.1

lr:
  value: 0.0001

epochs:
  value: 100

n_gpu:
  value: 1

feat_dim:
  value: 2304

n_classes:
  value: 60

n_workers:
  desc: Number of dataloader workers.
  value: 10